---

- name: Start 2 load-balanced containers
  docker_container:
    name: "{{ item }}"
    recreate: no
    image: library/nginx
  loop:
    - "nginx1"
    - "nginx2"
  register: containers


- name: Debugging
  debug:
    msg: "{{ item.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
  loop: "{{ containers.results }}"

- name: nginx configuration for site
  template: src=containers.conf dest=/etc/nginx/conf.d/containers.conf
